apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: cheapacr.azurecr.io/frontend:bc272514303c4be2c2f47a39ea9c2984385e7821
          name: frontend
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: frontend-secret
            - configMapRef:
                name: services-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
