apiVersion: x.getambassador.io/v3alpha1
kind: AmbassadorMapping
metadata:
  name: frontend
spec:
  hostname: "*"
  prefix: / # root
  timeout_ms: 10000
  service: kustomize-frontend:3000
  retry_policy:
    retry_on: "gateway-error"
    num_retries: 5
    per_try_timeout: 1s